# Generated by Django 2.2.16 on 2021-08-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='category name')),
                ('slug', models.SlugField(unique=True, verbose_name='category slug')),
            ],
        ),
    ]
