# Generated by Django 2.2.16 on 2021-08-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='title name')),
                ('year', models.IntegerField(verbose_name='year of issue')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000, verbose_name='title description')),
                ('category', models.ManyToManyField(related_name='titles', to='titles.Category')),
                ('genre', models.ManyToManyField(related_name='titles', to='titles.Genre')),
            ],
        ),
    ]
