# Generated by Django 2.2.16 on 2021-08-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
